# Generated by Django 6.0.7 on 2026-07-30 15:21

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('BLOOD', 'Blood Test Report'), ('URINE', 'Urine Test Report'), ('BIOCHEMISTRY', 'Biochemistry Report'), ('HAEMATOLOGY', 'Haematology Report'), ('OTHER', 'General Health Report')], default='BLOOD', max_length=30)),
                ('pdf_file', models.FileField(help_text='Only PDF files up to 5MB allowed', upload_to='medical_reports/', validators=[reports.models.validate_pdf_extension, reports.models.validate_max_file_size])),
                ('summary_notes', models.TextField(blank=True, null=True)),
                ('is_hard_copy_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='diagnostics.booking')),
                ('diagnostician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='diagnostics.diagnosticianprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
