# Generated by Django 6.0.7 on 2026-07-30 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_collection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Booking Confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician Assigned'), ('TECHNICIAN_ON_THE_WAY', 'Technician On The Way'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('REACHED_LABORATORY', 'Reached Laboratory'), ('TESTING', 'Testing'), ('REPORT_UPLOADED', 'Report Uploaded'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('collection_date', models.DateField()),
                ('collection_time', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Booking Confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician Assigned'), ('TECHNICIAN_ON_THE_WAY', 'Technician On The Way'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('REACHED_LABORATORY', 'Reached Laboratory'), ('TESTING', 'Testing'), ('REPORT_UPLOADED', 'Report Uploaded'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='diagnostics.booking')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('gst_number', models.CharField(max_length=50)),
                ('nabl_accredited', models.BooleanField(default=False)),
                ('working_hours', models.CharField(default='08:00 AM - 08:00 PM', max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lab_logos/')),
                ('is_home_collection_available', models.BooleanField(default=True)),
                ('is_approved_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='diagnostician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='diagnostics.diagnosticianprofile'),
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='General Diagnostics', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation', models.TextField(blank=True, help_text='e.g. 12 hours fasting required', null=True)),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Report turnaround time in hours')),
                ('is_home_collection_compatible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='diagnostics.diagnosticianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diagnostics.booking')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.diagnostictest')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='diagnostics.diagnosticianprofile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='diagnostics.technician'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diagnostics.cart')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.diagnostictest')),
            ],
            options={
                'unique_together': {('cart', 'test')},
            },
        ),
        migrations.CreateModel(
            name='SymptomTestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('frequency_weight', models.PositiveIntegerField(default=3, help_text='1 to 5 scale star weight')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='diagnostics.symptom')),
            ],
            options={
                'unique_together': {('symptom', 'test_name')},
            },
        ),
    ]
